HRL = \
	BasicDataType.hrl \
	oe_BasicDataType.hrl \
	oe_DataPort.hrl \
	oe_ExtendedDataTypes.hrl \
	oe_InterfaceDataTypes.hrl \
	oe_Manager.hrl \
	oe_OpenRTM.hrl \
	oe_RTC.hrl \
	oe_SDOPackage.hrl \
	OpenRTM_DataFlowComponent.hrl \
	OpenRTM_ExtTrigExecutionContextService.hrl \
	OpenRTM.hrl \
	OpenRTM_InPortCdr.hrl \
	OpenRTM_OutPortCdr.hrl \
	RTC_ComponentAction.hrl \
	RTC_DataFlowComponentAction.hrl \
	RTC_DataFlowComponent.hrl \
	RTC_ExecutionContext.hrl \
	RTC_ExecutionContextService.hrl \
	RTC_Fsm.hrl \
	RTC_FsmObject.hrl \
	RTC_FsmParticipantAction.hrl \
	RTC_FsmParticipant.hrl \
	RTC_FsmService.hrl \
	RTC.hrl \
	RTC_LightweightRTObject.hrl \
	RTC_ModeCapable.hrl \
	RTC_Mode.hrl \
	RTC_MultiModeComponentAction.hrl \
	RTC_MultiModeObject.hrl \
	RTC_PortService.hrl \
	RTC_RTObject.hrl \
	RTM.hrl \
	RTM_Manager.hrl \
	SDOPackage_Configuration.hrl \
	SDOPackage.hrl \
	SDOPackage_Organization.hrl \
	SDOPackage_SDO.hrl \
	SDOPackage_SDOService.hrl \
	SDOPackage_SDOSystemElement.hrl 
