MODULES = \
	oe_BasicDataType \
	oe_DataPort \
	oe_ExtendedDataTypes \
	oe_InterfaceDataTypes \
	oe_Manager \
	oe_OpenRTM \
	oe_RTC \
	oe_SDOPackage \
	OpenRTM_CdrData \
	OpenRTM_DataFlowComponent \
	OpenRTM_ExtTrigExecutionContextService \
	OpenRTM_InPortCdr \
	OpenRTM_OutPortCdr \
	RTC_Acceleration2D \
	RTC_Acceleration3D \
	RTC_ActArrayActuatorCurrent \
	RTC_ActArrayActuatorGeometry \
	RTC_ActArrayActuatorGeometryList \
	RTC_ActArrayActuatorPos \
	RTC_ActArrayActuatorSpeed \
	RTC_ActArrayGeometry \
	RTC_ActArrayState \
	RTC_Actuator \
	RTC_ActuatorList \
	RTC_AngularAcceleration3D \
	RTC_AngularVelocity3D \
	RTC_BumperArrayGeometry \
	RTC_BumperGeometry \
	RTC_BumperGeometryList \
	RTC_CameraImage \
	RTC_CameraInfo \
	RTC_Carlike \
	RTC_ComponentAction \
	RTC_ComponentProfile \
	RTC_ComponentProfileList \
	RTC_ConnectorProfile \
	RTC_ConnectorProfileList \
	RTC_Covariance2D \
	RTC_Covariance3D \
	RTC_DataFlowComponentAction \
	RTC_DataFlowComponent \
	RTC_ElementGeometryList \
	RTC_ExecutionContext \
	RTC_ExecutionContextList \
	RTC_ExecutionContextProfile \
	RTC_ExecutionContextProfileList \
	RTC_ExecutionContextService \
	RTC_ExecutionContextServiceList \
	RTC_Features \
	RTC_FiducialFOV \
	RTC_FiducialInfo \
	RTC_FiducialInfoList \
	RTC_Fiducials \
	RTC_FsmBehaviorProfile \
	RTC_FsmBehaviorProfileList \
	RTC_Fsm \
	RTC_FsmObject \
	RTC_FsmParticipantAction \
	RTC_FsmParticipant \
	RTC_FsmProfile \
	RTC_FsmService \
	RTC_Geometry2D \
	RTC_Geometry3D \
	RTC_GPSData \
	RTC_GPSTime \
	RTC_GripperGeometry \
	RTC_GripperState \
	RTC_Hypotheses2D \
	RTC_Hypotheses3D \
	RTC_Hypothesis2D \
	RTC_Hypothesis2DList \
	RTC_Hypothesis3D \
	RTC_Hypothesis3DList \
	RTC_INSData \
	RTC_IntensityData \
	RTC_IntensityList \
	RTC_LightweightRTObject \
	RTC_LimbState \
	RTC_LineFeature \
	RTC_LineFeatureList \
	RTC_ModeCapable \
	RTC_Mode \
	RTC_MulticameraGeometry \
	RTC_MulticameraGeometryList \
	RTC_MulticameraImageList \
	RTC_MultiCameraImages \
	RTC_MulticameraInfoList \
	RTC_MultiModeComponentAction \
	RTC_MultiModeObject \
	RTC_OAP \
	RTC_OGMapCells \
	RTC_OGMapConfig \
	RTC_OGMapTile \
	RTC_Orientation3D \
	RTC_PanTiltAngles \
	RTC_PanTiltState \
	RTC_Path2D \
	RTC_Path3D \
	RTC_Point2D \
	RTC_Point3D \
	RTC_PointCloud \
	RTC_PointCloudPoint \
	RTC_PointCloudPointList \
	RTC_PointCovariance2D \
	RTC_PointFeature \
	RTC_PointFeatureList \
	RTC_PortInterfaceProfile \
	RTC_PortInterfaceProfileList \
	RTC_PortProfile \
	RTC_PortProfileList \
	RTC_PortService \
	RTC_PortServiceList \
	RTC_Pose2D \
	RTC_Pose3D \
	RTC_PoseFeature \
	RTC_PoseFeatureList \
	RTC_PoseVel2D \
	RTC_PoseVel3D \
	RTC_RangeData \
	RTC_RangeList \
	RTC_RangerConfig \
	RTC_RangerGeometry \
	RTC_RFIDTagData \
	RTC_RGBColour \
	RTC_RTCList \
	RTC_RTObject \
	RTC_Size2D \
	RTC_Size3D \
	RTC_SpeedHeading2D \
	RTC_SpeedHeading3D \
	RTC_TimedAcceleration2D \
	RTC_TimedAcceleration3D \
	RTC_TimedAngularAcceleration3D \
	RTC_TimedAngularVelocity3D \
	RTC_TimedBoolean \
	RTC_TimedBooleanSeq \
	RTC_TimedCarlike \
	RTC_TimedChar \
	RTC_TimedCharSeq \
	RTC_TimedCovariance2D \
	RTC_TimedCovariance3D \
	RTC_TimedDouble \
	RTC_TimedDoubleSeq \
	RTC_TimedFloat \
	RTC_TimedFloatSeq \
	RTC_TimedGeometry2D \
	RTC_TimedGeometry3D \
	RTC_TimedLong \
	RTC_TimedLongSeq \
	RTC_TimedOAP \
	RTC_TimedOctet \
	RTC_TimedOctetSeq \
	RTC_TimedOrientation3D \
	RTC_TimedPoint2D \
	RTC_TimedPoint3D \
	RTC_TimedPointCovariance2D \
	RTC_TimedPose2D \
	RTC_TimedPose3D \
	RTC_TimedPoseVel2D \
	RTC_TimedPoseVel3D \
	RTC_TimedRGBColour \
	RTC_TimedShort \
	RTC_TimedShortSeq \
	RTC_TimedSize2D \
	RTC_TimedSize3D \
	RTC_TimedSpeedHeading2D \
	RTC_TimedSpeedHeading3D \
	RTC_TimedState \
	RTC_TimedString \
	RTC_TimedStringSeq \
	RTC_TimedULong \
	RTC_TimedULongSeq \
	RTC_TimedUShort \
	RTC_TimedUShortSeq \
	RTC_TimedVector2D \
	RTC_TimedVector3D \
	RTC_TimedVelocity2D \
	RTC_TimedVelocity3D \
	RTC_TimedWChar \
	RTC_TimedWCharSeq \
	RTC_TimedWString \
	RTC_TimedWStringSeq \
	RTC_Time \
	RTC_Vector2D \
	RTC_Vector3D \
	RTC_Velocity2D \
	RTC_Velocity3D \
	RTC_Waypoint2D \
	RTC_Waypoint2DList \
	RTC_Waypoint3D \
	RTC_Waypoint3DList \
	RTM_Manager \
	RTM_ManagerList \
	RTM_ManagerProfile \
	RTM_ModuleProfile \
	RTM_ModuleProfileList \
	SDOPackage_AllowedValues \
	SDOPackage_Configuration \
	SDOPackage_ConfigurationSet \
	SDOPackage_ConfigurationSetList \
	SDOPackage_DeviceProfile \
	SDOPackage_EnumerationType \
	SDOPackage_InterfaceNotImplemented \
	SDOPackage_InternalError \
	SDOPackage_IntervalType \
	SDOPackage_InvalidParameter \
	SDOPackage_NameValue \
	SDOPackage_NotAvailable \
	SDOPackage_Numeric \
	SDOPackage_NVList \
	SDOPackage_Organization \
	SDOPackage_OrganizationList \
	SDOPackage_OrganizationProperty \
	SDOPackage_Parameter \
	SDOPackage_ParameterList \
	SDOPackage_RangeType \
	SDOPackage_SDO \
	SDOPackage_SDOList \
	SDOPackage_SDOService \
	SDOPackage_SDOSystemElement \
	SDOPackage_ServiceProfile \
	SDOPackage_ServiceProfileList \
	SDOPackage_StringList 
